### ISSUE TITLE
Constants should be declared in the top of your program.

### ISSUE THREAD

**Issue by AlexKap23** [Drifta7/SlotMachine#1]
https://github.com/Drifta7/SlotMachine/blob/5f6177b29b3ba9f94a1df479873edf29888cb81b/Program.cs#L14-L17

Constants should be always declared on the top of your program. Since you are not familiar with classes yet, best place to declare them is in the first few lines of your main method.

Variables on the other hand should be declared as close to their first usage as possible. For example  numbersHasMactched is declared almost on top but you use it almost on the bottom. That makes the code more difficult to read as it requires more up and down scrolling. It's also difficult to remember initial values and you have to search for them.

So refactor the code a bit to follow the above practices

**Comment by Drifta7** [comment]
now constants are arranged to the top
