### ISSUE TITLE
User inputs should be always validated

### ISSUE THREAD

**Issue by AlexKap23** [Drifta7/SlotMachine#3]
https://github.com/Drifta7/SlotMachine/blob/5f6177b29b3ba9f94a1df479873edf29888cb81b/Program.cs#L30-L33

You are dealing with human inputs and humans do stupid things. What will happen in those lines if the input is a letter instead of a number? An exception will be thrown. 

Best approach is to validate the input **and even make** the user type something valid.

**Comment by Drifta7** [comment]
issue has been rectified , and now tryParse method catches user  input errors
