### ISSUE TITLE
Avoid hardcoded strings, use constants

### ISSUE THREAD

**Issue by AlexKap23** [Drifta7/SlotMachine#4]
https://github.com/Drifta7/SlotMachine/blob/5f6177b29b3ba9f94a1df479873edf29888cb81b/Program.cs#L186-L193

"y" and "n" here are options that may change if you decide to change them. Instead of using hardcoded values, you can declare constants for those with proper names like CONTINUE_PLAYING_POSITIVE_ANSWER for example.

**Comment by Drifta7** [comment]
now the constants now have been changed and reflect what a const is supposed to look like
